create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null,
  action text not null check (action in ('delete_empty_account')),
  target_user_id uuid not null,
  retained_user_id uuid,
  target_username text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_logs enable row level security;
grant select on public.admin_audit_logs to authenticated;

drop policy if exists "Administrators can read audit logs" on public.admin_audit_logs;
create policy "Administrators can read audit logs"
  on public.admin_audit_logs for select to authenticated
  using (public.is_superadmin());

create or replace function public.admin_delete_empty_account(
  target_user_id uuid,
  retained_user_id uuid,
  confirmation_username text
)
returns table (deleted_user_id uuid, deleted_username text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_name text;
  retained_name text;
  target_data jsonb := '{}'::jsonb;
  target_decks integer := 0;
  target_sessions integer := 0;
  target_matches integer := 0;
  recovery_blocked boolean := false;
begin
  if not public.is_superadmin() then
    raise exception using errcode = '42501', message = 'ADMIN_REQUIRED';
  end if;

  if target_user_id is null or retained_user_id is null or target_user_id = retained_user_id then
    raise exception using errcode = '22023', message = 'INVALID_ACCOUNT_SELECTION';
  end if;

  if target_user_id = (select auth.uid()) then
    raise exception using errcode = '42501', message = 'CANNOT_DELETE_SELF';
  end if;

  perform 1 from auth.users where id = target_user_id for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'ACCOUNT_NOT_FOUND';
  end if;

  perform 1 from auth.users where id = retained_user_id;
  if not found then
    raise exception using errcode = 'P0002', message = 'RETAINED_ACCOUNT_NOT_FOUND';
  end if;

  if exists (select 1 from public.admin_users where user_id = target_user_id) then
    raise exception using errcode = '42501', message = 'CANNOT_DELETE_ADMIN';
  end if;

  select profile.username
    into target_name
    from public.profiles as profile
   where profile.user_id = target_user_id;

  select profile.username
    into retained_name
    from public.profiles as profile
   where profile.user_id = retained_user_id;

  if target_name is null or retained_name is null
    or lower(btrim(target_name)) <> lower(btrim(retained_name)) then
    raise exception using errcode = '22023', message = 'DUPLICATE_ACCOUNT_MISMATCH';
  end if;

  if lower(btrim(coalesce(confirmation_username, ''))) <> lower(btrim(target_name)) then
    raise exception using errcode = '22023', message = 'USERNAME_CONFIRMATION_MISMATCH';
  end if;

  select coalesce(state.data, '{}'::jsonb)
    into target_data
    from public.app_states as state
   where state.user_id = target_user_id
     for update;

  target_data := coalesce(target_data, '{}'::jsonb);
  target_decks := case when jsonb_typeof(target_data -> 'decks') = 'array' then jsonb_array_length(target_data -> 'decks') else 0 end;
  target_sessions := case when jsonb_typeof(target_data -> 'sessions') = 'array' then jsonb_array_length(target_data -> 'sessions') else 0 end;
  target_matches := case when jsonb_typeof(target_data -> 'matches') = 'array' then jsonb_array_length(target_data -> 'matches') else 0 end;

  select exists (
    select 1
      from public.account_recovery_status as recovery
     where recovery.user_id = target_user_id
       and (
         recovery.status in ('detected', 'reviewing', 'saving', 'failed')
         or recovery.anonymous_decks > 0
         or recovery.anonymous_sessions > 0
         or recovery.anonymous_matches > 0
       )
  ) into recovery_blocked;

  if target_decks > 0 or target_sessions > 0 or target_matches > 0 or recovery_blocked then
    raise exception using errcode = 'P0001', message = 'ACCOUNT_NOT_EMPTY';
  end if;

  insert into public.admin_audit_logs (
    actor_user_id,
    action,
    target_user_id,
    retained_user_id,
    target_username,
    details
  ) values (
    (select auth.uid()),
    'delete_empty_account',
    target_user_id,
    retained_user_id,
    target_name,
    jsonb_build_object(
      'decks', target_decks,
      'sessions', target_sessions,
      'matches', target_matches
    )
  );

  delete from auth.users where id = target_user_id;
  if not found then
    raise exception using errcode = 'P0002', message = 'ACCOUNT_NOT_FOUND';
  end if;

  return query select target_user_id, target_name;
end;
$$;

revoke all on function public.admin_delete_empty_account(uuid, uuid, text) from public;
grant execute on function public.admin_delete_empty_account(uuid, uuid, text) to authenticated;
