create table if not exists public.app_state_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  data jsonb not null,
  source_updated_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists app_state_versions_user_created_idx
  on public.app_state_versions (user_id, created_at desc);

alter table public.app_state_versions enable row level security;
revoke all on public.app_state_versions from anon, authenticated;

create or replace function public.capture_app_state_version()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.app_state_versions (user_id, data, source_updated_at)
  values (old.user_id, old.data, old.updated_at);

  delete from public.app_state_versions
  where user_id = old.user_id
    and created_at < now() - interval '30 days';

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function public.capture_app_state_version() from public;

drop trigger if exists capture_app_state_version_before_change on public.app_states;
create trigger capture_app_state_version_before_change
  before update or delete on public.app_states
  for each row execute function public.capture_app_state_version();

insert into public.app_state_versions (user_id, data, source_updated_at)
select state.user_id, state.data, state.updated_at
from public.app_states as state
where not exists (
  select 1
  from public.app_state_versions as version
  where version.user_id = state.user_id
);
