create table if not exists public.environment_catalog (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 1 and 40),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.environment_catalog enable row level security;

grant select on public.environment_catalog to anon, authenticated;
grant insert, update, delete on public.environment_catalog to authenticated;
grant usage, select on sequence public.environment_catalog_id_seq to authenticated;

drop policy if exists "Anyone can read environment catalog" on public.environment_catalog;
create policy "Anyone can read environment catalog"
  on public.environment_catalog for select
  to anon, authenticated
  using (true);

drop policy if exists "Superadmins can insert environments" on public.environment_catalog;
create policy "Superadmins can insert environments"
  on public.environment_catalog for insert
  to authenticated
  with check (public.is_superadmin());

drop policy if exists "Superadmins can update environments" on public.environment_catalog;
create policy "Superadmins can update environments"
  on public.environment_catalog for update
  to authenticated
  using (public.is_superadmin())
  with check (public.is_superadmin());

drop policy if exists "Superadmins can delete environments" on public.environment_catalog;
create policy "Superadmins can delete environments"
  on public.environment_catalog for delete
  to authenticated
  using (public.is_superadmin());

insert into public.environment_catalog (name, sort_order)
select environment_name, (row_number() over (order by environment_name) * 10)::integer
from (
  select distinct trim(session ->> 'environment') as environment_name
  from public.app_states as app_state
  cross join lateral jsonb_array_elements(coalesce(app_state.data -> 'sessions', '[]'::jsonb)) as session
) as existing
where environment_name is not null
  and environment_name not in ('', '未設定', '現環境')
on conflict (name) do nothing;

create or replace function public.get_admin_environment_catalog()
returns table (id bigint, name text, sort_order integer, active boolean, usage_count bigint)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_superadmin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  return query
  select
    catalog.id,
    catalog.name,
    catalog.sort_order,
    catalog.active,
    (
      select count(*)
      from public.app_states as app_state
      cross join lateral jsonb_array_elements(coalesce(app_state.data -> 'sessions', '[]'::jsonb)) as session
      where session ->> 'environment' = catalog.name
    )::bigint as usage_count
  from public.environment_catalog as catalog
  order by catalog.sort_order, catalog.created_at;
end;
$$;

revoke all on function public.get_admin_environment_catalog() from public;
grant execute on function public.get_admin_environment_catalog() to authenticated;

create or replace function public.admin_add_environment(environment_name text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_name text := trim(environment_name);
begin
  if not public.is_superadmin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if char_length(normalized_name) < 1 or char_length(normalized_name) > 40 then
    raise exception 'Environment name must be between 1 and 40 characters';
  end if;

  insert into public.environment_catalog (name, sort_order)
  values (
    normalized_name,
    coalesce((select max(catalog.sort_order) + 10 from public.environment_catalog as catalog), 10)
  );
end;
$$;

revoke all on function public.admin_add_environment(text) from public;
grant execute on function public.admin_add_environment(text) to authenticated;

create or replace function public.admin_rename_environment(current_name text, next_name text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_current text := trim(current_name);
  normalized_next text := trim(next_name);
  app_state record;
  rewritten_sessions jsonb;
  rewritten_environments jsonb;
begin
  if not public.is_superadmin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if normalized_current = normalized_next then
    return;
  end if;
  if char_length(normalized_next) < 1 or char_length(normalized_next) > 40 then
    raise exception 'Environment name must be between 1 and 40 characters';
  end if;
  if not exists (select 1 from public.environment_catalog where name = normalized_current) then
    raise exception 'Environment not found';
  end if;
  if exists (select 1 from public.environment_catalog where name = normalized_next) then
    delete from public.environment_catalog where name = normalized_current;
  else
    update public.environment_catalog
    set name = normalized_next, updated_at = now()
    where name = normalized_current;
  end if;

  for app_state in
    select user_id, data
    from public.app_states
    where exists (
      select 1
      from jsonb_array_elements(coalesce(data -> 'sessions', '[]'::jsonb)) as session
      where session ->> 'environment' = normalized_current
    )
    or coalesce(data -> 'environments', '[]'::jsonb) ? normalized_current
  loop
    select coalesce(
      jsonb_agg(
        case
          when session ->> 'environment' = normalized_current
            then jsonb_set(session, '{environment}', to_jsonb(normalized_next::text), true)
          else session
        end
        order by ordinal
      ),
      '[]'::jsonb
    )
    into rewritten_sessions
    from jsonb_array_elements(coalesce(app_state.data -> 'sessions', '[]'::jsonb))
      with ordinality as sessions(session, ordinal);

    select coalesce(
      jsonb_agg(
        case
          when environment #>> '{}' = normalized_current then to_jsonb(normalized_next::text)
          else environment
        end
        order by ordinal
      ),
      '[]'::jsonb
    )
    into rewritten_environments
    from jsonb_array_elements(coalesce(app_state.data -> 'environments', '[]'::jsonb))
      with ordinality as environments(environment, ordinal);

    update public.app_states
    set data = jsonb_set(
      jsonb_set(app_state.data, '{sessions}', rewritten_sessions, true),
      '{environments}',
      rewritten_environments,
      true
    ),
    updated_at = now()
    where user_id = app_state.user_id;
  end loop;
end;
$$;

revoke all on function public.admin_rename_environment(text, text) from public;
grant execute on function public.admin_rename_environment(text, text) to authenticated;

create or replace function public.admin_delete_environment(environment_name text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_name text := trim(environment_name);
begin
  if not public.is_superadmin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if exists (
    select 1
    from public.app_states as app_state
    cross join lateral jsonb_array_elements(coalesce(app_state.data -> 'sessions', '[]'::jsonb)) as session
    where session ->> 'environment' = normalized_name
  ) then
    raise exception 'Environment is in use and cannot be deleted';
  end if;

  delete from public.environment_catalog where name = normalized_name;
end;
$$;

revoke all on function public.admin_delete_environment(text) from public;
grant execute on function public.admin_delete_environment(text) to authenticated;
