create table if not exists public.app_states (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 2 and 20),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.account_consents (
  user_id uuid primary key references auth.users(id) on delete cascade,
  terms_version text not null,
  accepted_at timestamptz not null default now(),
  ai_training_included boolean not null default true
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('superadmin')),
  created_at timestamptz not null default now()
);

create table if not exists public.environment_catalog (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 1 and 40),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.app_states enable row level security;
alter table public.profiles enable row level security;
alter table public.account_consents enable row level security;
alter table public.admin_users enable row level security;
alter table public.environment_catalog enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.app_states to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.account_consents to authenticated;
grant select on public.admin_users to authenticated;
grant select on public.environment_catalog to anon, authenticated;
grant insert, update, delete on public.environment_catalog to authenticated;
grant usage, select on sequence public.environment_catalog_id_seq to authenticated;

create or replace function public.is_superadmin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
      and role = 'superadmin'
  );
$$;

revoke all on function public.is_superadmin() from public;
grant execute on function public.is_superadmin() to authenticated;

create or replace function public.get_admin_app_states()
returns table (user_id uuid, data jsonb, updated_at timestamptz)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_superadmin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  return query
  select
    state.user_id,
    jsonb_build_object(
      'decks', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', deck -> 'id',
          'name', deck -> 'name'
        ))
        from jsonb_array_elements(coalesce(state.data -> 'decks', '[]'::jsonb)) as deck
      ), '[]'::jsonb),
      'sessions', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', session -> 'id',
          'deckId', session -> 'deckId',
          'environment', session -> 'environment'
        ))
        from jsonb_array_elements(coalesce(state.data -> 'sessions', '[]'::jsonb)) as session
      ), '[]'::jsonb),
      'matches', coalesce((
        select jsonb_agg(jsonb_build_object(
          'sessionId', match -> 'sessionId',
          'myDeck', match -> 'myDeck',
          'opponentDeck', match -> 'opponentDeck',
          'result', match -> 'result',
          'firstPlayer', match -> 'firstPlayer',
          'opponentRps', match -> 'opponentRps',
          'myPassed', match -> 'myPassed',
          'opponentPassed', match -> 'opponentPassed'
        ))
        from jsonb_array_elements(coalesce(state.data -> 'matches', '[]'::jsonb)) as match
      ), '[]'::jsonb)
    ),
    state.updated_at
  from public.app_states as state;
end;
$$;

revoke all on function public.get_admin_app_states() from public;
grant execute on function public.get_admin_app_states() to authenticated;

create or replace function public.get_admin_user_state(target_user_id uuid)
returns table (data jsonb, updated_at timestamptz)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_superadmin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  return query
  select state.data, state.updated_at
  from public.app_states as state
  where state.user_id = target_user_id;
end;
$$;

revoke all on function public.get_admin_user_state(uuid) from public;
grant execute on function public.get_admin_user_state(uuid) to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_username text;
begin
  requested_username := nullif(trim(new.raw_user_meta_data ->> 'username'), '');
  if requested_username is null then
    requested_username := left(split_part(coalesce(new.email, 'user'), '@', 1), 20);
  end if;
  if char_length(requested_username) < 2 then
    requested_username := 'ユーザー';
  end if;

  insert into public.profiles (user_id, username)
  values (new.id, left(requested_username, 20))
  on conflict (user_id) do nothing;

  if coalesce(new.raw_user_meta_data ->> 'terms_accepted', 'false') = 'true' then
    insert into public.account_consents (user_id, terms_version, accepted_at, ai_training_included)
    values (
      new.id,
      coalesce(nullif(new.raw_user_meta_data ->> 'terms_version', ''), 'unknown'),
      now(),
      true
    )
    on conflict (user_id) do nothing;
  end if;

  if lower(coalesce(new.email, '')) = '0harry0wilder0@gmail.com' then
    insert into public.admin_users (user_id, role)
    values (new.id, 'superadmin')
    on conflict (user_id) do update set role = excluded.role;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

insert into public.profiles (user_id, username)
select
  id,
  case
    when char_length(left(coalesce(nullif(trim(raw_user_meta_data ->> 'username'), ''), split_part(coalesce(email, 'user'), '@', 1), 'ユーザー'), 20)) < 2 then 'ユーザー'
    else left(coalesce(nullif(trim(raw_user_meta_data ->> 'username'), ''), split_part(coalesce(email, 'user'), '@', 1), 'ユーザー'), 20)
  end
from auth.users
on conflict (user_id) do nothing;

insert into public.admin_users (user_id, role)
select id, 'superadmin'
from auth.users
where lower(email) = '0harry0wilder0@gmail.com'
on conflict (user_id) do update set role = excluded.role;

drop policy if exists "Users can read their own app state" on public.app_states;
create policy "Users can read their own app state"
  on public.app_states for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own app state" on public.app_states;
create policy "Users can insert their own app state"
  on public.app_states for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own app state" on public.app_states;
create policy "Users can update their own app state"
  on public.app_states for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own app state" on public.app_states;
create policy "Users can delete their own app state"
  on public.app_states for delete to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can read profiles" on public.profiles;
create policy "Users can read profiles"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = user_id or public.is_superadmin());

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
  on public.profiles for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own profile" on public.profiles;
create policy "Users can delete their own profile"
  on public.profiles for delete to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can read consents" on public.account_consents;
create policy "Users can read consents"
  on public.account_consents for select to authenticated
  using ((select auth.uid()) = user_id or public.is_superadmin());

drop policy if exists "Users can insert their own consent" on public.account_consents;
create policy "Users can insert their own consent"
  on public.account_consents for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own consent" on public.account_consents;
create policy "Users can update their own consent"
  on public.account_consents for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can read their own admin role" on public.admin_users;
create policy "Users can read their own admin role"
  on public.admin_users for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Anyone can read environment catalog" on public.environment_catalog;
create policy "Anyone can read environment catalog"
  on public.environment_catalog for select
  to anon, authenticated
  using (true);

drop policy if exists "Superadmins can insert environments" on public.environment_catalog;
create policy "Superadmins can insert environments"
  on public.environment_catalog for insert
  to authenticated
  with check (public.is_superadmin());

drop policy if exists "Superadmins can update environments" on public.environment_catalog;
create policy "Superadmins can update environments"
  on public.environment_catalog for update
  to authenticated
  using (public.is_superadmin())
  with check (public.is_superadmin());

drop policy if exists "Superadmins can delete environments" on public.environment_catalog;
create policy "Superadmins can delete environments"
  on public.environment_catalog for delete
  to authenticated
  using (public.is_superadmin());

insert into public.environment_catalog (name, sort_order)
select environment_name, (row_number() over (order by environment_name) * 10)::integer
from (
  select distinct trim(session ->> 'environment') as environment_name
  from public.app_states as app_state
  cross join lateral jsonb_array_elements(coalesce(app_state.data -> 'sessions', '[]'::jsonb)) as session
) as existing
where environment_name is not null
  and environment_name not in ('', '未設定', '現環境')
on conflict (name) do nothing;

create or replace function public.get_admin_environment_catalog()
returns table (id bigint, name text, sort_order integer, active boolean, usage_count bigint)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_superadmin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  return query
  select
    catalog.id,
    catalog.name,
    catalog.sort_order,
    catalog.active,
    (
      select count(*)
      from public.app_states as app_state
      cross join lateral jsonb_array_elements(coalesce(app_state.data -> 'sessions', '[]'::jsonb)) as session
      where session ->> 'environment' = catalog.name
    )::bigint as usage_count
  from public.environment_catalog as catalog
  order by catalog.sort_order, catalog.created_at;
end;
$$;

revoke all on function public.get_admin_environment_catalog() from public;
grant execute on function public.get_admin_environment_catalog() to authenticated;

create or replace function public.admin_add_environment(environment_name text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_name text := trim(environment_name);
begin
  if not public.is_superadmin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if char_length(normalized_name) < 1 or char_length(normalized_name) > 40 then
    raise exception 'Environment name must be between 1 and 40 characters';
  end if;

  insert into public.environment_catalog (name, sort_order)
  values (
    normalized_name,
    coalesce((select max(catalog.sort_order) + 10 from public.environment_catalog as catalog), 10)
  );
end;
$$;

revoke all on function public.admin_add_environment(text) from public;
grant execute on function public.admin_add_environment(text) to authenticated;

create or replace function public.admin_rename_environment(current_name text, next_name text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_current text := trim(current_name);
  normalized_next text := trim(next_name);
  app_state record;
  rewritten_sessions jsonb;
  rewritten_environments jsonb;
begin
  if not public.is_superadmin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if normalized_current = normalized_next then
    return;
  end if;
  if char_length(normalized_next) < 1 or char_length(normalized_next) > 40 then
    raise exception 'Environment name must be between 1 and 40 characters';
  end if;
  if not exists (select 1 from public.environment_catalog where name = normalized_current) then
    raise exception 'Environment not found';
  end if;

  if exists (select 1 from public.environment_catalog where name = normalized_next) then
    delete from public.environment_catalog where name = normalized_current;
  else
    update public.environment_catalog
    set name = normalized_next, updated_at = now()
    where name = normalized_current;
  end if;

  for app_state in
    select user_id, data
    from public.app_states
    where exists (
      select 1
      from jsonb_array_elements(coalesce(data -> 'sessions', '[]'::jsonb)) as session
      where session ->> 'environment' = normalized_current
    )
    or coalesce(data -> 'environments', '[]'::jsonb) ? normalized_current
  loop
    select coalesce(
      jsonb_agg(
        case
          when session ->> 'environment' = normalized_current
            then jsonb_set(session, '{environment}', to_jsonb(normalized_next::text), true)
          else session
        end
        order by ordinal
      ),
      '[]'::jsonb
    )
    into rewritten_sessions
    from jsonb_array_elements(coalesce(app_state.data -> 'sessions', '[]'::jsonb))
      with ordinality as sessions(session, ordinal);

    select coalesce(
      jsonb_agg(
        case
          when environment #>> '{}' = normalized_current then to_jsonb(normalized_next::text)
          else environment
        end
        order by ordinal
      ),
      '[]'::jsonb
    )
    into rewritten_environments
    from jsonb_array_elements(coalesce(app_state.data -> 'environments', '[]'::jsonb))
      with ordinality as environments(environment, ordinal);

    update public.app_states
    set data = jsonb_set(
      jsonb_set(app_state.data, '{sessions}', rewritten_sessions, true),
      '{environments}',
      rewritten_environments,
      true
    ),
    updated_at = now()
    where user_id = app_state.user_id;
  end loop;
end;
$$;

revoke all on function public.admin_rename_environment(text, text) from public;
grant execute on function public.admin_rename_environment(text, text) to authenticated;

create or replace function public.admin_delete_environment(environment_name text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_name text := trim(environment_name);
begin
  if not public.is_superadmin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if exists (
    select 1
    from public.app_states as app_state
    cross join lateral jsonb_array_elements(coalesce(app_state.data -> 'sessions', '[]'::jsonb)) as session
    where session ->> 'environment' = normalized_name
  ) then
    raise exception 'Environment is in use and cannot be deleted';
  end if;

  delete from public.environment_catalog where name = normalized_name;
end;
$$;

revoke all on function public.admin_delete_environment(text) from public;
grant execute on function public.admin_delete_environment(text) to authenticated;
